[package]
name = "zakat-calculator-BE"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
tokio = "1.41.1"
sqlite = "0.36.1"
serde = { version = "1.0.215", features = ["derive"] }
